motors:
  joint_1:
    id: 1
    model: sts3215
    homing_offset: -55
    range_min: 0
    range_max: 4095
  joint_2:
    id: 2
    model: sts3215
    homing_offset: 244
    range_min: 923
    range_max: 3211
  joint_3:
    id: 3
    model: sts3215
    homing_offset: -1243
    range_min: 869
    range_max: 3247
  joint_4:
    id: 4
    model: sts3215
    homing_offset: 1442
    range_min: 2047
    range_max: 3074
